### ISSUE TITLE
unexpected error message "error unmarshalling content" if package does not exist

### ISSUE THREAD

**Issue by vielmetti** [google/nixery#11]
Tried to run the example by loading two packages, `curl` and `nc`. Alas there is no `nc` (it's called `netcat`). The error message was unexpected.

```
emv@bastion-0:~$ sudo docker run -ti nixery.appspot.com/shell/curl/nc bash
Unable to find image 'nixery.appspot.com/shell/curl/nc:latest' locally
docker: Error response from daemon: error unmarshalling content: unexpected end of JSON input.
See 'docker run --help'.
```

I'm not sure what the right thing to do is here (but it's probably not this unexpected error).

**Comment by vielmetti** [comment]
From the looks of it, the relevant error is triggered here

https://github.com/google/nixery/blob/master/main.go#L179

**Comment by tazjin** [comment]
Hey, thanks for reporting this!

The actual unmarshaling issue comes from inside of the Docker client. Nixery somewhat blindly responds with whatever structure is returned by the Nix build, and since non-existent packages currently cause the Nix build [to abort](https://github.com/google/nixery/blob/8dc407cc7490d90ffec6d90ee6ad67f685575d9e/build-registry-image.nix#L66) the returned structure will be incorrect.

One of the ways forward for this would be to collect such errors inside of Nix and pass them on to the server in the build output structure. The server could inspect this input and respond with reasonable error messages.
