### ISSUE TITLE
Uppercase characters in in package names

### ISSUE THREAD

**Issue by mgttlinger** [google/nixery#14]
How would you specify packages that contain uppercase characters like e.g. `minisatUnstable` given that Docker rejects those URLs stating that they should be all lowercase?
```
invalid reference format: repository name must be lowercase.
```

I also tried `minisat-unstable` which failed with 
```
Error response from daemon: error unmarshalling content: unexpected end of JSON input.
```

This also is an issue for specifying programming language packages living e.g. under `haskellPackages` or `ocamlPackages`.

**Comment by tazjin** [comment]
Hey, thanks for logging this. I'd run into it before, but forgotten about it.

This might be a bit more involved because there is no simple way to do case-insensitive lookups in attribute sets in Nix (afaik).

A potential solution could look like this:

1. We define one canonical format for specifying these (e.g. all lowercase)
2. If the Nix code fails to look up an entry, it creates a mapping from a normalised representation of attribute set keys that match certain criteria (e.g. uppercase characters) to the "actual" keys and uses that instead.

Potential problems:

* the chosen representation might have conflicts inside of the package set
* it's non-obvious for users, but there's probably not much we can do other than document it

-------

The error you received is due to #11 - problems aren't fed back to Docker with the correct status codes (e.g. 404 for packages not found) yet.

**Comment by tazjin** [comment]
Further digging. I used this code to evaluate whether there are any attribute set entries that would end up duplicated if we normalised the names:

```nix
# Does nixpkgs have keys that would be duplicates if everything was
# lowercased?

with builtins; let
  pkgs = import <nixpkgs> {};
  names = attrNames pkgs;

  incFrom = attrs: name: if hasAttr name attrs
  then (attrs // { "${name}" = (attrs."${name}" + 1); })
  else (attrs // { "${name}" = 1; });

  counted = foldl' incFrom {} (map pkgs.lib.toLower names);
in {
  result = pkgs.lib.filterAttrs (_: v: v > 1) counted;
}
```

The result is (somewhat unsurprisingly): Yes!

```
~/p/nixery (master↑4|…) $ nix eval -f dups.nix result 
{ flamegraph = 2; ppsspp = 2; qmidinet = 2; }
```

Upon investigation it turned out that the differently cased versions are actually aliases for the same thing. Doing the same transformation with `haskellPackages` however reveals a wide range of packages with conflicting names that *do not* yield the same package, for example `haskellPackages.yocto` and `haskellPackages.Yocto`.

I'm not yet sure what to make of this. For now I might apply this normalisation to the top-level if an attribute is not found, but not for nested keys (i.e. you can refer to `haskellpackages` but not to `haskellPackages.Yocto`, only `haskellPackages.yocto`) - but this decision isn't final yet.
