### ISSUE TITLE
documentation: over-escaped vertical bars in nix-1p

### ISSUE THREAD

**Issue by das-g** [google/nixery#44]
On https://nixery.dev/nix-1p.html#operators, the "logical `AND`" operator is displayed as `|\|` and the "Logical implication" operator is explained as being equivalent to `!e1 \|\| e2`. These should be `||` and `!e1 || e2` instead, respectively.

On https://github.com/tazjin/nix-1p/blob/master/README.md#operators they are displayed correctly, so I guess that GitHub and the nixery.dev documentation rendering process assume different MarkDown dialects.

**Comment by das-g** [comment]
mdBook ([as of 0.3.1](https://github.com/rust-lang-nursery/mdBook/blob/v0.3.1/Cargo.toml#L29)) uses pulldown-cmark, which according to rust-lang-nursery/mdBook#822 goes beyond the CommonMark specification. (It has to, to have native table support.)

GitHub probably still uses "GitHub flavored MarkDown".

**Comment by tazjin** [comment]
Hey, thanks for reporting and also digging into this!

This issue is a bit annoying, but at least we don't have to choose *where* to fix it as the Github documentation rendering is static while we have control over mdBook.

Two tasks:

* [ ] Work around this by `sed`-ing (or whatever) the input during the docs build
* [ ] Determine whether this is a bug in one or either components, or whether they're both living up to their individual specifications

**Comment by tazjin** [comment]
I did some experimentation and it seems like the Markdown parser in mdBook doesn't have any way of escaping the pipe character inside of a table, inside of a code block. This might be a bug in the parser, but for now I can work around it by making a change in `nix-1p`.

**Comment by tazjin** [comment]
FYI the fix is deployed to nixery.dev
