### ISSUE TITLE
Can we use the nixery.dev service?

### ISSUE THREAD

**Issue by chrissound** [google/nixery#67]
Many thanks for making this project - seems very cool indeed! :) I'm just wondering, if you're happy to be providing the nixery.dev service publicly? Or would you prefer individuals setup their own nixery instance? 

I mean it's currently public - but it's not 100% clear if this is just for testing / demonstration purpose.

**Comment by tazjin** [comment]
Hey Chris,

sorry for the late reply - last week was a bit hectic and I'm still catching up with things!

The public instance is provided with no service or support guarantees from Google (Nixery is not an officially supported project), but other than a temporary technical failure there should be no reason for it to go down. You will have to decide whether that risk is acceptable to you.

[Setting up a private instance](https://nixery.dev/run-your-own.html) is what I would recommend you to do if you plan to rely on it for production use-cases. Since NixCon is happening this week and I'm talking about Nixery there, there'll be some more docs about setup on GKE and such coming out very soon.

Cheers!
